---
networks:
  service:
    external: true

services:

  proxy:
    image: proxy:dev
    build:
      context: .
      target: proxy
    container_name: proxy
    hostname: proxy.${HOSTNAME:?}
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.rule: Host(`proxy.${HOSTNAME:?}`)
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.tls.certresolver: ${CERT_RESOLVER:?}
      traefik.http.routers.dashboard.middlewares: auth
      traefik.http.services.dashboard.loadbalancer.server.port: 8080
      traefik.http.middlewares.auth.basicauth.users: ${TRAEFIK_AUTH:?}
    entrypoint: ['sh', '/etc/traefik/entrypoint.sh']
    env_file:
      - .env
    ports:
      - 3306:3306
      - 443:443
      - 80:80
      - 8080:8080
    volumes:
      - ./proxy/traefik:/etc/traefik/
      - certs:/etc/traefik/certs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - service
    profiles:
      - proxy

  cert-watcher:
    image: alpine:latest
    depends_on:
      - proxy
    container_name: cert-watcher
    entrypoint:
      - /app/entrypoint.sh
      - /etc/traefik/certs
      - ${CERT_RESOLVER:?}
    volumes:
      - certs:/etc/traefik/certs
      - ./proxy/cert-watcher/entrypoint.sh:/app/entrypoint.sh
    restart: always
    networks:
      - service
    profiles:
      - proxy

  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql.${HOSTNAME:?}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
    labels:
      traefik.enable: true
      traefik.http.routers.mysql.rule: Host(`mysql.${HOSTNAME:?}`)
      traefik.http.routers.mysql.entrypoints: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - service
    profiles:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin.${HOSTNAME:?}
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    labels:
      traefik.enable: true
      traefik.http.routers.phpmyadmin.rule: Host(`phpmyadmin.${HOSTNAME:?}`)
      traefik.http.routers.phpmyadmin.entrypoints: websecure
      traefik.http.routers.phpmyadmin.tls.certresolver: ${CERT_RESOLVER:?}
    restart: always
    networks:
      - service
    profiles:
      - mysql

volumes:
  certs:
  mysql:
