---
- name: Check environment variables
  fail:
    msg: 'Environment variable {{ item }} must be set'
  when: lookup('env', item) == ''
  loop:
    - ADMIN_EMAIL

- name: Register environment variables
  set_fact:
    admin_email: '{{ lookup("env", "ADMIN_EMAIL") }}'
